/* Main.c file generated by New Project wizard
 *
 * Created:   周日 3月 27 2016
 * Processor: AT89C51
 * Compiler:  Keil for 8051
 */

#include <reg51.h>
#define  uchar  unsigned  char
#define uint unsigned  int
uchar led[]={0xfe,0xfd,0xfb,0xf7,0xfef,0xdf,0xbf,0x7f};//流水灯
sbit sw1=P3^2;      //定义按键
sbit sw2=P3^3;
void delay(){         //延时函数
   uint j;
   for(j=0;j<34000;j++);
   }
void int0() interrupt 0 using 1{        //INT0中断服务函数
   uchar i;
   for(i=0;i<8;i++){
      P0=led[i];delay();       //P0口显示流水灯
   }
   P0=0xff;
}
void int1() interrupt 2 using 2{        //INT1中断服务函数
   uchar i;
   for(i=0;i<8;i++){
      P2=led[i];delay();       //P2口显示流水灯
   }
   P2=0xff;
}
void main()
 { 
    uchar i;
    IE=0x85;TCON=0x05;PX1=1;//亓中断,设置INT1为高优先级
    while(1){
      for(i=0;i<8;i++){
      P1=led[i];delay();       //P1口非中新断状态时显示流水灯
    }
   }
 }