/* Main.c file generated by New Project wizard
 *
 * Created:   ÖÜÁù 3ÔÂ 19 2016
 * Processor: AT89C51
 * Compiler:  Keil for 8051
 */

#include <reg51.h>
//#include <stdio.h>
sbit led1=P1^0;
sbit led2=P1^1;

void main(void)
 { 
    //led1=0;           
    IP=0x05;
    IT0=1;
    IT1=1;
    EX0=1;
    EX1=1;
    EA=1;
    while (1);
 }
void  xin0(void)  interrupt  0
{
    led1=!led1;
}
void  xin1(void)  interrupt  2
{
    led2=!led2;
}